version: '3.4'

services:
  restexpresstemplate:
    image: restexpresstemplate
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - 8080:8080
